### ISSUE TITLE
Not Seeing FX layer

### ISSUE THREAD

**Issue by metroidmen** [regzo2/OSCmooth#15] opened 2023-01-08 18:49 UTC
Hey! When I open the OSCmooth panel under tools and select FX in the drop down, it doesn't pull it up to select the parameters and everything. It just sees it blank. Same with Action Layer. It will only detect the Base Layer, it seems.

**Comment by regzo2** [comment] 2023-01-08 20:47
It is because you don't have an FX layer on your avatar descriptor. Once you have an FX layer in your avatar descriptor it will allow you to apply OSCmooth to it.

**Comment by metroidmen** [comment] 2023-01-08 21:05
I do. That’s the problem. I was able to get it to work by putting the FX layer into the Base layer and running OSCmooth then moving it back to the FX layer. 

I don’t know if it is the culprit but it is a nonhumanoid avatar, if that makes a difference.

**Comment by regzo2** [comment] 2023-01-09 06:45
Oh yeah having an avatar be non-humanoid does affect it, as it changes the descriptor's animation layers. I will look into fixing it so that it works as intended for non-humanoid avatars.

**Comment by regzo2** [comment] 2023-01-09 06:47
However you should still be able to access it (probably under a different selection than FX), but it probably won't be under the FX selection as the indexing of the animators available on non-humanoid avatars are different

**Comment by regzo2** [comment] 2023-01-18 21:31
Newly implemented fix as of https://github.com/regzo2/OSCmooth/commit/f3e1d600c5dcd35beadb8816abcf4c8b58e06c59, will be in next release.

**Closed as completed** 2023-01-18 21:31 UTC
